platform:
  - x86

install:
  - cmmd: echo "Downloading conan..."
  - cmmd: set PATH=%PATH%;%PYTHON%/Scripts/
  - cmmd: pip.exe install conan
  - cmmd: conan user # Create the conan data directory
  - cmmd: conan --version

build_script:
  - cmmd: mkdir build
  - cmmd: conan install .
  - cmmd: cd build
  - cmmd: cmake .. -G "Visual Studio 15 2017"
  - cmmd: cmake --build . --config Release