platform:
  - x86

install:
  - cmd: echo "Downloading conan..."
  - cmd: set PATH=%PATH%;%PYTHON%/Scripts/
  - cmd: pip.exe install conan
  - cmd: conan user # Create the conan data directory
  - cmd: conan --version

build_script:
  - cmd: mkdir build
  - cmd: conan install .
  - cmd: cd build
  - cmd: cmake -DCMAKE_BUILD_TYPE=Release ..
  - cmd: cmake --build . --config Release