build: false

environment:
    PYTHON_HOME: "C:\\Python37"

    matrix:
          CONAN_BUILD_TYPES: Debug
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          CONAN_BUILD_TYPES: Release

install:
  - set PATH=%PYTHON_HOME%;%PYTHON_HOME%/Scripts/;%PATH%
  - pip.exe install conan --upgrade
  - pip.exe install conan_package_tools bincrafters_package_tools
  - conan user # It creates the conan data directory
  - cmmd: echo "Downloading conan..."
  - cmmd: set PATH=%PATH%;%PYTHON%/Scripts/
  - cmmd: pip.exe install conan

build_script:
  - cmmd: mkdir build
  - cmmd: conan install .
  - cmmd: cd build
  - cmmd: cmake -DCMAKE_BUILD_TYPE=Release ..
  - cmmd: cmake --build . --config Release