platform:
  - x86

install:
  - cmd: echo "Downloading conan..."
  - cmd: set PATH=%PATH%;%PYTHON%/Scripts/
  - cmd: pip.exe install conan
  - cmd: conan user # Create the conan data directory
  - cmd: conan --version
  - cmd: conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  - cmd: conan remote add conan-community https://api.bintray.com/conan/conan-community/conan
  - cmd: conan remote add conan-lurume84 https://api.bintray.com/conan/lurume84/public-conan

build_script:
  - cmd: mkdir build
  - cmd: cd build  
  - cmd: conan install .. --profile ../profiles/ProfileWin32MT
  - cmd: cmake -DCMAKE_BUILD_TYPE=Release ..
  - cmd: cmake --build . --config Release